import java.util.function.Supplier;

/**
 * @author Tyler James and Julia Schaming
 */
public class Main{

    public static void main(String[] args) {
        // Can create Boards of type "classic", "pyramid", and "fish"
        Board board = new Board(238493280, "classic");

        // Run BeamStack search
        BeamStack beamStack = new BeamStack(2, 2);
        // System.out.print(beamStack.runInstance(board, 1));

        // Run AStar search with smaller board generated by beamStack
        // Average aStarStart board is about 30 moves away from the goal state
        Board aStarStart = beamStack.getSmallerBoard(board, 1);
        AStar aStar = new AStar();
        aStar.runInstance(aStarStart, 2);
    }
    
    public static Board recordRuntime(Supplier<Board> function) {
        float startTime = System.currentTimeMillis();
        Board result = function.get();
        float endTime = System.currentTimeMillis();
        float runtime = endTime - startTime;
        System.out.printf("Time taken: %.02f ms\n", runtime);
        return result;
    }
}